name: Merge Code in PROD Branch

on:
  push:
    branches:
      - DEV

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Merge DEV Branch
      run: |
        git merge origin/DEV --no-ff
    - name: Push to PROD Branch
      run: |
        git push origin HEAD:PROD
